### ISSUE TITLE
suggest increasing maximum of 'segments to approximate' > 99

### ISSUE THREAD

**Issue by stevefaeembra** [HeikkiVesanto/QGIS_Multi_Ring_Buffer#3]
this is great - it automates what I've been trying to do with parallel lines around shores.

one limit I find is that with detailed shorelines when zoomed in, the maximum quality setting of 99 isn't enough. Of course I can simplify the shoreline, but is there any reason why it's capped at 99?

**Comment by HeikkiVesanto** [comment]
Hi Steve,

Capped at 99 because the QGIS buffer tool is capped at 99 (Vector>Geoprocessing Tools>Buffer(s)...), so I don't know how well it would handle more than 99?

Any thoughts?

**Comment by stevefaeembra** [comment]
gosh, you're right... so it won't be any worse than what I'm doing at the moment!

I thought this might be a GUI element setting rather than something with the underlying code - I've followed the C# code trail but couldn't find source for GEOSBufferWithStyle_r(). Not seen anything to suggest a hard limit before it gets that far. 

I'll try tweaking my local copy to see if it can handle more than 99. I'd expect it to take longer, of course (which may have been the reasoning behind such a low limit in the first place)

**Comment by stevefaeembra** [comment]
I tweaked the UI file and ramped it up to 300 to get an acceptable result at the scale and shape detail level I was after.

Took a long time though - 5 minutes on a polygon with 10000 nodes, to do 5 rings 100m apart. Each ring takes longer than the last, which makes sense.

Looks like there's headroom for improved buffering quality for those prepared to hack and with sufficient patience ;-)

**Comment by HeikkiVesanto** [comment]
Increased to 300 as per suggetion.

I have added a new advanced tab where you can choose the "central" style. I think that might work better with very high vertex counts. Each ring shouldnt be much longer than the last.

See:
https://rawgit.com/HeikkiVesanto/QGIS_Multi_Ring_Buffer/master/help/index.html
