### ISSUE TITLE
Multi Ring Buffer not saving properly.

### ISSUE THREAD

**Issue by michaelkirk** [HeikkiVesanto/QGIS_Multi_Ring_Buffer#4]
Love the extension.

I'm not having issues creating the ring buffers initially, but once I save the layer, there seems to be some trouble.

The green is the layer generated by the plugin. The blue is the result of saving that layer to shapefile. Notice how all but the inner ring feature are missing?

<img width="1160" alt="screen shot 2015-10-07 at 5 30 07 pm" src="https://cloud.githubusercontent.com/assets/217057/10354775/61cc2572-6d18-11e5-8edb-65e673586c28.png">

To reproduce:
1. Started with set of 8358 points (non-bridge_freeway_ramp_intersections).
2. Created a multi-ring buffer at 500ft, with 10 layers.
   ![screen shot 2015-10-07 at 5 31 30 pm](https://cloud.githubusercontent.com/assets/217057/10354788/951ff340-6d18-11e5-912e-22dd6db61552.png)
3. MultiRingBuffer layer renders (after a few minutes).
4. Save the newly created MultiRingBuffer layer to a shapefile
5. New shapfile has all the features in the attributes table, but only a subset of rings is rendered. I've had different results when running this multiple times. Sometimes _most_ of the rings will render. Sometimes just one. Interestingly the feature count is still there.

**Comment by HeikkiVesanto** [comment]
Hi Michael,

It sounds like the features are being created if the feature counts match,
just not being shown.

Can you try turning off feature simplification?
Settings>Options>Rendering>Turn on feature simplification by default for
new layers (untick).

Then if you restart QGIS and try the buffer again.

Let me know if that resolves the issue.

-Heikki

**Comment by michaelkirk** [comment]
Hello @HeikkiVesanto!

I did try turning off feature simplification and still saw jagged edges. Furthermore there were points between the spaces in the jagged ring buffers which were not intersecting with any ring buffer. 

For my analysis I actually wanted concentric overlapping circles (no hole, not donuts) so I ended up just creating a bunch of buffers manually and merging the features into one shapefile.

I'm going to close this for now as I'm no longer pursuing this approach. Thanks!

**Comment by michaelkirk** [comment]
I'm reivisiting this plugin, and still experienced this issue. I started to update my bug report, but then realized that I hadn't read your instructions carefully. I'd disabled simplification for the layer _after_ saving it, and that didn't help. But, as you said, disabling simplification at the application level for _new_ layers fixed the problem. Thank you!

For posterity, here's a screenshot of what I was seeing:

![screen shot 2015-10-27 at 3 44 15 pm](https://cloud.githubusercontent.com/assets/217057/10774935/c681b7d0-7cc1-11e5-92a4-c4e0005b868a.png)

I disabled rendering:simplify geometry for the _layer_ (but this was insufficient).
![screen shot 2015-10-27 at 3 47 19 pm](https://cloud.githubusercontent.com/assets/217057/10774978/1682dcc8-7cc2-11e5-8d1c-56a66e7b5840.png)

Here are my MultiRingBuffer settings:
![screen shot 2015-10-27 at 3 49 21 pm](https://cloud.githubusercontent.com/assets/217057/10775017/5cdd1c4c-7cc2-11e5-9315-d93eb08d3071.png)

![screen shot 2015-10-27 at 3 49 25 pm](https://cloud.githubusercontent.com/assets/217057/10775018/5ce3d668-7cc2-11e5-9c9c-0487bbc5ac48.png)

Using QGis 2.10 on Mac

```

QGIS version
2.10.1-Pisa
QGIS code revision

Compiled against Qt
4.8.6
Running against Qt
4.8.6
Compiled against GDAL/OGR
1.11.2
Running against GDAL/OGR
1.11.2
Compiled against GEOS
3.4.2-CAPI-1.8.2
Running against GEOS
3.4.2-CAPI-1.8.2 r3921
PostgreSQL Client Version
9.4.4
SpatiaLite Version
4.2.0
QWT Version
6.0.2
PROJ.4 Version
491
QScintilla2 Version
2.9
```

**Comment by HeikkiVesanto** [comment]
Hi Michael,

The multi-ring buffer creates a lot of vertices and as such QGIS can try to
simplify it a little too much. Another work-around, which might work, if
you are creating buffers with a lot of rings is to use the "Central" buffer
style from the Advanced tab.

But I'm glad that resolved it.
