### ISSUE TITLE
Attributes of input vector

### ISSUE THREAD

**Issue by jflabelle1** [HeikkiVesanto/QGIS_Multi_Ring_Buffer#5]
The multi ring buffer tool doesn't keep the attributes of the input vector in the output file. Is there a way to do so?

**Comment by HeikkiVesanto** [comment]
With version 0.3 the attributes are now copied over. See https://gis.stackexchange.com/questions/250891/multiple-ring-buffer-for-multiple-points/250923#250923 for way to manually install. Or wait for approval in the plugin repo.

Sorry for the delay. Was moving countries and was hoping to hold off updates until QGIS 3.0.
