### ISSUE TITLE
QGIS 3 version will not buffer either a memory layer or any other layer in my tests

### ISSUE THREAD

**Issue by rjwillson** [HeikkiVesanto/QGIS_Multi_Ring_Buffer#8]
QGIS 3 version will not buffer either a memory layer or any other layer in my tests so far and I haven't been able to successfully use plugin since upgraded to Q3. Generates python errors but no buffers 

using QGIS on windows 10

**Comment by HeikkiVesanto** [comment]
Cheers. Posting the error message would be helpful for future bug reports. But I think I know what you mean.

The plugin was converted using version 2.99 of QGIS. There were some API breaks between 2.99 and 3.

I have a new version submitted to the official repository, awaiting approval, should be there in the next couple of days. Alternatively you can download the version in this repository and place it into:

C:\Users\YOUR_USER_NAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Multi_Ring_Buffer

**Comment by rjwillson** [comment]
I downloaded the repository and generating the buffers work perfectly now - Thanks!

**Comment by HeikkiVesanto** [comment]
Version 1.1 is live in the official report now please upgrade and let me know if there are any further issues.
